### ISSUE TITLE
Add a title for this blog

### ISSUE THREAD

**Issue by salander0411** [lab798/GATK-Best-Practice-on-AWS#2]
Qualified & detailed content!

Really deserve a good title for this :)

**Comment by hy714335634** [comment]
Thank you for your advice，I've already added a title

**Comment by hy714335634** [comment]
> Qualified & detailed content!
> 
> Really deserve a good title for this :)

Thank you for your advice，I've already added a title

**Comment by hy714335634** [comment]
@salander0411 
Thank you for your advice，I've already added a title
